language: d
d:
  - dmd
  - dmd-2.095.1
  - ldc

jobs:
  include:
    - stage: build
      script: $DMD -g -of=thread_pool src/mmutils/thread_pool.d -version=Test
    - stage: test
      script: ./thread_pool
    - stage: deploy
      local_dir: ./docs
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: true
      on:
        branch: master

