language: d
d:
  - dmd-2.095.1
  - ldc

jobs:
  include:
    - stage: test
    - stage: deploy
      local_dir: ./docs
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: true
      on:
        branch: master

